apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  imageURL: https://storage.googleapis.com/runwhen-nonprod-shared-images/icons/azure/general/10035-icon-service-Resource-Groups.svg
  alias: {{ match_resource.resource_group.name }} Azure Resource Group Health
  asMeasuredBy: Count of unused resource groups (no resources and no activity)
  configProvided:
  - name: SLX_PLACEHOLDER
    value: SLX_PLACEHOLDER
  owners:
  - {{workspace.owner_email}}
  statement: The health of Azure Resource Groups is measured by identifying unused resource groups (those with no resources and no activity in the specified lookback period).
  additionalContext:
    name: "{{match_resource.resource.name}}"
    qualified_name: "{{ match_resource.qualified_name }}"
    resource_group: "{{ match_resource.resource_group.name }}"
    subscription_id: "{{ match_resource.subscription_id }}"
  tags:
    - name: cloud
      value: azure
    - name: service
      value: resource-group
    - name: access
      value: read-only